plugins {
    id "com.android.application"
}

android {
    namespace "com.lforderbook.monitor"
    compileSdk 35

    defaultConfig {
        applicationId "com.lforderbook.monitor"
        minSdk 24
        targetSdk 34
        versionCode 6
        versionName "2.4.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
        }
    }
}
